version: '3.8'

services:
  database:
    image: postgres:15
    container_name: dbPostgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./dataDatabase:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=12345
volumes:
  dataDatabase: