import { ReactNode } from 'react'
import '../styles/globals.css'

import {
  Roboto_Flex as Roboto,
  Bai_Jamjuree as Baijamjuree
} from 'next/font/google'

import AuthSessionProvider from '@/context/sessionProvider'





// DEFINIR AS FONTES:
const roboto = Roboto({
  subsets: ['latin'],
  weight: '100',
  variable: '--font-roboto'
})
const baijamjuree = Baijamjuree({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-bai-jamjuree'
})



export const metadata = {
  title: 'Page',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt">

      <body className={`${roboto.variable} ${baijamjuree.variable} font-sans`}>
        <AuthSessionProvider>
          {/* <h1>layout raiz</h1> */}
          {children}
        </AuthSessionProvider>
      </body>

    </html>
  )
}